GITHUB_ID: 'your information here'
GITHUB_SECRET: 'your information here'
TWITTER_CONSUMER_KEY: 'your information here'
TWITTER_CONSUMER_SECRET: 'your information here'
TWITTER_OAUTH_TOKEN: 'your information here'
TWITTER_OAUTH_TOKEN_SECRET: 'your information here'
