development:
  adapter: your_db
  encoding: unicode
  database: teamline_development
  pool: 5
  username: your_username
  password:
  host: localhost

test:
  adapter: your_db
  encoding: unicode
  database: teamline_test
  pool: 5
  username: your_username
  password:
  host: localhost

production:
  adapter: your_db
  database: teamline_production
  host: localhost
  username: teamline
  password: teamline
  pool: 5
  timeout: 5000