development:
  adapter: postgresql
  encoding: unicode
  database: teamline_development
  pool: 5
  username: 
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: teamline_test
  pool: 5
  username: 
  password:
  host: localhost

production:
  adapter: postgresql
  database: teamline_production
  host: localhost
  username: 
  password: 
  pool: 5
  timeout: 5000